#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"


function install_patched_powerline_fonts() {
  local clone_dir="$(dotfiles_location)/dependencies/fonts"

  if [ ! -d "$clone_dir" ]; then
    echo "Setting up patched Powerline fonts..."
    git clone git@github.com:powerline/fonts.git "$clone_dir"

    $clone_dir/install.sh
  fi

  cd $(dotfiles_location)
}

function install_nerd_fonts() {
  local nerd_fonts_dir="$(dotfiles_location)/dependencies/patched-nerd-fonts"

  if [ ! -d $nerd_fonts_dir ]; then
    echo "Pulling in patched nerd-fonts..."

    mkdir -p $nerd_fonts_dir

    cd $nerd_fonts_dir && \
      git init && \
      mkdir -p .git/info && \
      git remote add origin https://github.com/ryanoasis/nerd-fonts.git && \
      git config core.sparsecheckout true && \
      echo "patched-fonts/*" >> .git/info/sparse-checkout && \
      git pull --depth=1 origin master

    cd $(dotfiles_location)

    local destination=$HOME/Library/Fonts

    find $nerd_fonts_dir -iname "*.ttf" -exec cp {} "$destination" \;
  fi
}

dotheader "Setting up fonts..."

install_patched_powerline_fonts
install_nerd_fonts