#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if test ! $(which brew); then
  echo "Installing homebrew"

  ruby -e "$(curl -fsSL \
    https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

dotheader "Setting up Homebrew..."